# Generated by Django 2.2.7 on 2019-12-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('isRegister', models.BooleanField()),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
