# Generated by Django 2.2.7 on 2019-12-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191216_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='isRegister',
            field=models.BooleanField(default=True),
        ),
    ]
