# Generated by Django 2.2.5 on 2019-12-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191216_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=50)),
                ('course_credits', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=50)),
                ('room_cap', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teach_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('teach_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='std_email',
            field=models.EmailField(default='16201519-001@uog.edu.pk', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='std_password',
            field=models.CharField(default='16201519-001', max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='rollno',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
