# Generated by Django 2.2.5 on 2019-12-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20191218_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='teach_designation',
            field=models.CharField(choices=[('AL', 'Assistant Lecturer '), ('L', 'Lecturer '), ('AP', 'Assistant Professor'), ('P', 'Professor')], default='designation', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_cap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teach_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
