# Generated by Django 2.2.7 on 2019-12-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='date',
        ),
    ]
