# Generated by Django 2.2.7 on 2019-12-14 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0002_remove_complaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='complaint',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
